-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.on("hyprland.start", function()
    hl.exec_cmd("swaybg -o eDP-1 -i /home/jakob/Bilder/Wallpapers/hyprland-nebula.png -m fill")
    hl.exec_cmd("hypridle")
    hl.exec_cmd("~/.config/hypr/scripts/ac-sound-watch.sh")
    hl.exec_cmd("~/.config/hypr/scripts/wob-init.sh")
    hl.exec_cmd("eww daemon")
    hl.exec_cmd("waybar")
    hl.exec_cmd("swaync")
    hl.exec_cmd("/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1")
    hl.exec_cmd("sh -c 'SSH_AUTH_SOCK=$XDG_RUNTIME_DIR/ssh-agent.socket ssh-add ~/.ssh/id_ed25519'")
end)

