-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

-- Source: ~/.config/hypr/monitors.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("monitors")
-- Source: ~/.config/hypr/input.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("input")
-- Source: ~/.config/hypr/keybinds.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("keybinds")
-- Source: ~/.config/hypr/rules.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("rules")
-- Source: ~/.config/hypr/autostart.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("autostart")

-- Snabb/snappy tempo (~150-200ms), rät kurva utan overshoot — se
-- vault/04-tema/design.md för resonemanget bakom bytet från easeOutCubic (~300ms)
hl.curve("snappy", { type = "bezier", points = { { 0.2, 0.9 }, { 0.3, 1 } } })
hl.animation({
    leaf = "windows",
    enabled = true,
    speed = 3,
    bezier = "snappy",
    style = "popin 80%",
})
hl.animation({
    leaf = "windowsOut",
    enabled = true,
    speed = 3,
    bezier = "snappy",
    style = "popin 80%",
})
hl.animation({
    leaf = "border",
    enabled = true,
    speed = 4,
    bezier = "default",
})
hl.animation({
    leaf = "fade",
    enabled = true,
    speed = 3,
    bezier = "snappy",
})
hl.animation({
    leaf = "workspaces",
    enabled = true,
    speed = 3,
    bezier = "snappy",
    style = "slide",
})
hl.animation({
    leaf = "specialWorkspace",
    enabled = true,
    speed = 3,
    bezier = "snappy",
    style = "slidevert",
})

hl.config({
    general = {
        gaps_in = 8,
        gaps_out = 14,
        border_size = 1,
        layout = "dwindle",
        ["col.active_border"] = "rgba(3f5c42ff)",
        ["col.inactive_border"] = "rgba(93a08c33)",
    },
    decoration = {
        rounding = 18,
        active_opacity = 0.92,
        inactive_opacity = 0.62,
        shadow = {
            enabled = true,
            range = 12,
            render_power = 2,
            color = "rgba(00000055)",
        },
        blur = {
            enabled = true,
            size = 8,
            passes = 3,
            new_optimizations = true,
            ignore_opacity = true,
        },
    },
    animations = {
        enabled = true,
    },
    misc = {
        vrr = 1,
        disable_hyprland_logo = true,
        disable_splash_rendering = true,
    },
    xwayland = {
        force_zero_scaling = true,
    },
})

