-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

-- Source: ~/.config/hypr/monitors.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("monitors")
-- Source: ~/.config/hypr/input.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("input")
-- Source: ~/.config/hypr/keybinds.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("keybinds")
-- Source: ~/.config/hypr/rules.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("rules")
-- Source: ~/.config/hypr/autostart.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("autostart")

hl.curve("easeOutCubic", { type = "bezier", points = { { 0.33, 1 }, { 0.68, 1 } } })
hl.curve("easeInOutCubic", { type = "bezier", points = { { 0.65, 0 }, { 0.35, 1 } } })
hl.animation({
    leaf = "windows",
    enabled = true,
    speed = 4,
    bezier = "easeOutCubic",
    style = "popin 80%",
})
hl.animation({
    leaf = "windowsOut",
    enabled = true,
    speed = 4,
    bezier = "easeOutCubic",
    style = "popin 80%",
})
hl.animation({
    leaf = "border",
    enabled = true,
    speed = 6,
    bezier = "default",
})
hl.animation({
    leaf = "fade",
    enabled = true,
    speed = 4,
    bezier = "easeOutCubic",
})
hl.animation({
    leaf = "workspaces",
    enabled = true,
    speed = 4,
    bezier = "easeInOutCubic",
    style = "slide",
})
hl.animation({
    leaf = "specialWorkspace",
    enabled = true,
    speed = 4,
    bezier = "easeOutCubic",
    style = "slidevert",
})

hl.config({
    general = {
        gaps_in = 5,
        gaps_out = 10,
        border_size = 2,
        layout = "dwindle",
    },
    decoration = {
        rounding = 8,
        active_opacity = 1.0,
        inactive_opacity = 0.94,
        shadow = {
            enabled = true,
            range = 12,
            render_power = 2,
            color = "rgba(00000055)",
        },
        blur = {
            enabled = true,
            size = 6,
            passes = 2,
            new_optimizations = true,
            ignore_opacity = true,
        },
    },
    animations = {
        enabled = true,
    },
    misc = {
        vrr = 1,
        disable_hyprland_logo = true,
        disable_splash_rendering = true,
    },
    xwayland = {
        force_zero_scaling = true,
    },
})

