-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.config({
    input = {
        kb_layout = "se",
        follow_mouse = 1,
        sensitivity = 0,
        touchpad = {
            natural_scroll = false,
            tap_to_click = true,
            disable_while_typing = true,
            scroll_factor = 0.8,
        },
    },
})

