-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.window_rule({
    match = {
        class = "^(Rofi)$",
    },
    opacity = 0.82,
})

hl.window_rule({
    match = {
        class = "^(btop-float)$",
    },
    float = true,
    size = "900 600",
    center = true,
})

hl.layer_rule({
    match = { namespace = "^(swaync-notification-window)$" },
    blur = true,
})

hl.layer_rule({
    match = { namespace = "^(swaync-control-center)$" },
    blur = true,
})

hl.layer_rule({
    match = { namespace = "^(wob)$" },
    blur = true,
})

hl.layer_rule({
    match = { namespace = "^(waybar)$" },
    blur = true,
})

