exec-once = swaybg -o eDP-1 -i /home/jakob/Bilder/Wallpapers/hyprland-nebula.png -m fill
exec-once = hypridle
exec-once = eww daemon
exec-once = waybar
exec-once = swaync
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
