background {
    monitor =
    path = screenshot
    blur_passes = 2
    blur_size = 6
    noise = 0.02
    brightness = 0.55
}

general {
    hide_cursor = false
}

label {
    monitor =
    text = cmd[update:1000] echo "$(date +'%H:%M')"
    color = rgba(232, 241, 255, 1.0)
    font_size = 90
    font_family = JetBrainsMono Nerd Font
    position = 0, 160
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:60000] echo "$(date +'%A %d %B')"
    color = rgba(113, 128, 157, 1.0)
    font_size = 20
    font_family = JetBrainsMono Nerd Font
    position = 0, 60
    halign = center
    valign = center
}

input-field {
    monitor =
    size = 300, 55
    outline_thickness = 2
    dots_size = 0.25
    dots_spacing = 0.3
    outer_color = rgba(98, 230, 255, 0.6)
    inner_color = rgba(7, 9, 16, 0.85)
    font_color = rgba(232, 241, 255, 1.0)
    check_color = rgba(98, 230, 255, 1.0)
    fail_color = rgba(255, 84, 112, 1.0)
    placeholder_text = <span foreground="##71809d">Lösenord...</span>
    rounding = 14
    position = 0, -80
    halign = center
    valign = center
}
