windowrule = match:class ^(Rofi)$, opacity 0.88

windowrule = match:class ^(btop-float)$, float 1, size 900 600, center 1

layerrule = blur 1, match:namespace ^(swaync-notification-window)$
layerrule = blur 1, match:namespace ^(swaync-control-center)$